fixtures:
  symlinks:
    avahi: "#{source_dir}"
  forge_modules:
    bodgitlib:
      repo: "bodgit/bodgitlib"
      ref: "3.0.1"
    dbus:
      repo: "bodgit/dbus"
      ref: "3.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "7.1.0"
  repositories:
    augeasproviders_core:
      repo: "https://github.com/hercules-team/augeasproviders_core.git"
      ref: "2.7.0"
