fixtures:
  symlinks:
    avahi: "#{source_dir}"
  forge_modules:
    augeasproviders_core:
      repo: "herculesteam/augeasproviders_core"
      ref: "2.6.0"
    bodgitlib:
      repo: "bodgit/bodgitlib"
      ref: "1.5.0"
    dbus:
      repo: "bodgit/dbus"
      ref: "2.0.0"
    ip:
      repo: "thrnio/ip"
      ref: "1.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.13.0"
